# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

  # Runs Set Single Commands using Shell
    steps:
    - uses: actions/checkout@v4
    - name: Run a one-line script
      run: echo Hello World!

    # Runs Set Of Multiple Commands using Shell
    - name: Run Multiple Line Commands
      run: 
        echo Hello World! Second Time
        echo test and deploy code
